import os
import requests
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain.tools import tool
from langchain_core.messages import ToolMessage
from tavily import TavilyClient
from rich import print
from langchain.agents import create_agent 
from langchain.agents.middleware import wrap_tool_call

# Load environment variables from your .env file
load_dotenv()

# TOOL 1: Weather Tool (OpenWeatherMap API)

@tool
def get_weather(city: str) -> str:
    """Get current weather of a city"""
    
    api_key = os.getenv("OPENWEATHER_API_KEY")
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city},IN&appid={api_key}&units=metric"
    
    response = requests.get(url)
    data = response.json()
    
    # Check if the API returned an error code
    if str(data.get("cod")) != "200":
        return f"Error: {data.get('message', 'Could not fetch weather')}"
    
    temp = data["main"]["temp"]
    desc = data["weather"][0]["description"]
    
    return f"Weather in {city}: {desc}, {temp}°C"

# TOOL 2: News Tool (Tavily Search API)

tavily_client = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))

@tool
def get_news(city: str) -> str:
    """Get latest news about a city"""
    
    response = tavily_client.search(
        query=f"latest news in {city}",
        search_depth="advanced",
        max_results=3
    )
    
    results = response.get("results", [])
    
    if not results:
        return f"No news found for {city}"
    
    news_list = []
    
    for r in results:
        title = r.get("title", "No title")
        url = r.get("url", "")
        snippet = r.get("content", "")
        
        news_list.append(
            f"- {title}\n  URL: {url}\n  Snippet: {snippet[:100]}..."
        )
    
    return f"Latest news in {city}:\n\n" + "\n\n".join(news_list)



#: Groq Integration

# Initializing ChatGroq
llm = ChatGroq(model="meta-llama/llama-4-scout-17b-16e-instruct")

# MIDDLEWARE: Human-In-The-Loop Approval

@wrap_tool_call
def human_approval(request, handler):
    """
    Intercepts the agent loop right before a tool is executed.
    Asks the user for terminal validation before proceeding.
    """
    tool_name = request.tool_call["name"]
    confirm = input(f"\n[System Alert] Agent wants to call tool '{tool_name}'. Approve? (yes/no): ")

    # If user types anything other than 'yes', we intercept execution
    # and feed a cancellation message back to the LLM.
    if confirm.lower() != "yes":
        return ToolMessage(
            content="Tool call denied by user.",
            tool_call_id=request.tool_call["id"]
        )

    # If approved, handler(request) lets the tool run normally.
    return handler(request)  

# AGENT COMPILATION

# Using LangChain's factory to bind the LLM, tools, and the human gate middleware.
agent = create_agent(
    llm,
    tools=[get_weather, get_news],
    system_prompt="You are a helpful city assistant.",
    middleware=[human_approval]
)

# APPLICATION LOOP

print("[bold green]City Agent Initialized! Type 'exit' to quit.[/bold green]")

while True:
    user_input = input("\nYou : ")
    if user_input.lower() == "exit":
        break 
        
    # Send user query to the agent graph loop
    result = agent.invoke({
        "messages": [{"role": "user", "content": user_input}]
    })

    # Display the final text response generated by the model
    print("\nbot : ", result['messages'][-1].content)